version: "3.3"
services:
  app:
    build: .
    container_name: directus-cicd
    volumes:
      - ../directus_share:/directus/uploads
    env_file:
      - ../configs/directus.env
    image: sacconazzo/directus-cicd
    restart: always
    ports:
      - "${PORT:-8055}:8055"
      - "${PORT_FE:-5000}:5000"
    environment:
      - PORT=8055
