services:
  app:
    build: .
    container_name: directus-cicd
    volumes:
      - "${DIRECTUS_SHARE:-../directus_share}:/workspace/directus/uploads"
    env_file:
      - "${DIRECTUS_ENV:-../config/.env}"
    image: sacconazzo/directus-cicd
    restart: always
    ports:
      - "${PORT:-8055}:8055"
      - "${PORT_FE:-5000}:5000"
